package com.ztrios.opd_doctor_service.enums;

import java.util.Arrays;
import java.util.stream.Collectors;

public enum Specialization {
    // Your original values
    GENERAL_PRACTICE,
    CARDIOLOGY,
    DERMATOLOGY,
    NEUROLOGY,
    PEDIATRICS,
    ORTHOPEDICS,
    ONCOLOGY,

    // Additional common specializations
    ANESTHESIOLOGY,
    CARDIOTHORACIC_SURGERY,
    DENTISTRY,
    DERMATOLOGIC_SURGERY,
    EMERGENCY_MEDICINE,
    ENDOCRINOLOGY,
    FAMILY_MEDICINE,
    GASTROENTEROLOGY,
    GENERAL_SURGERY,
    GERIATRICS,
    HEMATOLOGY,
    INFECTIOUS_DISEASE,
    INTERNAL_MEDICINE,
    NEPHROLOGY,
    NEUROSURGERY,
    NUCLEAR_MEDICINE,
    OBSTETRICS_GYNECOLOGY,
    OCCUPATIONAL_MEDICINE,
    OPHTHALMOLOGY,
    ORAL_SURGERY,
    ORTHODONTICS,
    OTOLARYNGOLOGY,
    PATHOLOGY,
    PEDIATRIC_SURGERY,
    PHYSICAL_MEDICINE,
    PLASTIC_SURGERY,
    PODIATRY,
    PREVENTIVE_MEDICINE,
    PSYCHIATRY,
    PULMONOLOGY,
    RADIATION_ONCOLOGY,
    RADIOLOGY,
    RHEUMATOLOGY,
    SPORTS_MEDICINE,
    THORACIC_SURGERY,
    UROLOGY,
    VASCULAR_SURGERY,

    // Sub-specialties
    ALLERGY_IMMUNOLOGY,
    BREAST_SURGERY,
    CARDIAC_ELECTROPHYSIOLOGY,
    CHILD_NEUROLOGY,
    CLINICAL_NEUROPHYSIOLOGY,
    COLORECTAL_SURGERY,
    CRITICAL_CARE_MEDICINE,
    DERMATOPATHOLOGY,
    FETAL_MEDICINE,
    HAND_SURGERY,
    HEAD_NECK_SURGERY,
    HEPATOLOGY,
    INTERVENTIONAL_CARDIOLOGY,
    INTERVENTIONAL_RADIOLOGY,
    MATERNAL_FETAL_MEDICINE,
    MEDICAL_ONCOLOGY,
    NEONATOLOGY,
    NEUROCRITICAL_CARE,
    NEUROLOGICAL_SURGERY,
    NEUROOPHTHALMOLOGY,
    NEURORADIOLOGY,
    PAIN_MEDICINE,
    PEDIATRIC_ALLERGY,
    PEDIATRIC_CARDIOLOGY,
    PEDIATRIC_ENDOCRINOLOGY,
    PEDIATRIC_GASTROENTEROLOGY,
    PEDIATRIC_HEMATOLOGY_ONCOLOGY,
    PEDIATRIC_NEPHROLOGY,
    PEDIATRIC_PULMONOLOGY,
    PEDIATRIC_RHEUMATOLOGY,
    PEDIATRIC_UROLOGY,
    REPRODUCTIVE_ENDOCRINOLOGY,
    SLEEP_MEDICINE,
    SPINAL_SURGERY,
    SURGICAL_ONCOLOGY,
    TRAUMA_SURGERY,
    TRANSplant_SURGERY,
    WOMENS_HEALTH;

    // Optional: Add display names
    public String getDisplayName() {
        return Arrays.stream(name().split("_"))
                .map(word -> word.charAt(0) + word.substring(1).toLowerCase())
                .collect(Collectors.joining(" "));
    }
}
